jobteaser/circleci

orbs/docker/orb.yml

Some websites suggest to use directly vcs-url and vcs-ref.
http://label-schema.org/rc1/ documents the org.label-schema. prefix, but
also says that it is deprecated in favour of OCI. OCI says
(https://github.com/opencontainers/image-spec/blob/master/annotations.md)
that we should use org.opencontainers.image.revision and
org.opencontainers.image.url. So OCI it is :)

add the git url and git hash as labels to docker images

---

orbs/changelog/orb.yml

Voilà, non mais ho, fallait pas me chauffer :-) A mort bash, vive Node !
I maintain generate_slack_release_notes until I finalized the PR https://github.com/jobteaser-oss/slack-release-note/pull/1

Use generate_slack_release_notes to generate a better slack release note

---

.circleci/config.yml

There should be no issues on letting whatever branch to be published as dev orb.

chore: remove restriction on dev orbs publishing

---

orbs/docker/orb.yml

Sets the default docker version used to 18.09.3 which allows using buildkit
As discussed, we'd rather want most people to use the same docker version, to avoid chasing bugs in many docker versions. So I removed the `docker_version` parameter.
For future reference, if one really needs to use another docker version [1], inside your repository's `.circleci/config.yml`:
- (keep) import(ing) this orb;
- cut paste the `build_image` [job](https://circleci.com/docs/2.0/configuration-reference/#jobs), found in the docker orb, into your config file ;
- prefix the steps names in the job with `docker/` (to reference the orbs commands);
- "inline" the `setup` step and change the `version` value;
- If you were already calling `docker/build_image` in any of your …

Change docker version used to 18.09.3  

---

utils/configure-project

Adds a -n argument to the command line to let one override the kubernetes namespace name that defaults to the repository/service name.
Also include some shell syntax fixes.
Closes #39

Allow overriding the namespace name

---

orbs/helm/orb.yml

For machine learning base deployments, the pods can take some time to be ready.
For instance, [JobMatch](https://github.com/jobteaser/jobmatch) takes a couple of hours to embed all the job ads and students on the first run.
Therefore, in the CI, one would like to disable the `--wait` option in `helm upgrade`, so that the deploy job is still successful, even if the pod is not ready.
@cansjt @jobteaser/squad-foundation What do you think about it?

Make --wait optional in helm upgrade

---

orbs/github/orb.yml

This PR copy some logic for deployment tagging, contained in helm orb, into its own dedicated orb. This will allow to re-use tagging commands in another repository that is not based on Helm.
(I tested this orb on a feature env deployment)

feat(github-tag): Put logic for tag deployment in dedicated orb

---

.circleci/config.yml

This PR fixes the following issue: the publishing of stable orbs is never done because the `validate` job that `publish_stable` job depends on is never run by CircleCI (by default CircleCI does NOT trigger builds for tags - see https://circleci.com/docs/2.0/configuration-reference/#tags).

fix(build-tag-on-ci): tags are not built on CI as expected

---

orbs/circleci/Dockerfile.concurrent
orbs/circleci/circle-wait-job
orbs/circleci/deployable
orbs/circleci/orb.yml

This PR copies some logic for concurrent deployment on production, in a dedicated Orb (copied from `helm` Orb). It also improve a bit the strategy to avoid a possible deadlock that happens when 2 deployment jobs are waiting for each other (happens sometimes on the monolith today).
This new dedicated orb was initially created to be used in frontend repo `ui-jobteaser` but it could really be used anywhere.
This concurrent deployment feature is exposed as a job `circleci/concurrent_build_management` that must be called before the "deploy" job of a given project.
Ex:
```yaml
- circleci/concurrent_build_management:
name: "concurrent_build_management"
context: "deploy_prod"
requires: ["lint_js", "lint_css", "test_js", "build"]
filters:
branches:
only:
- master
job_name: "deploy_prod" …
```

feat(orb-circleci): create dedicated orb for concurrent deployment management

---

orbs/helm/orb.yml

Add the ability to shunt the 'Wait for all other builds to complete' step. Default remains to waiting for other pending builds.

Allow parallel deployments

---

orbs/e2e-web/orb.yml

It will be used to clone master branch for dev repo, but current branch on jt_e2e_tests repo

Branch management for the e2e orb

---

orbs/e2e-web/orb.yml

I have removed tags from executor to be able to use it as parameter.
I have added a specific check before running e2e steps. For ui-jobteaser only, we run the script which is in the repo, which will parse all files of the commit and set tags regarding impacted folders.
If not, we will use the tags which is send in parameters.

New orb version to handle scripts to find specific tags to run

---

orbs/helm/orb.yml

Because all Job_classifier CI deployments are currently failing because of no output timeout.
Eg. https://github.com/jobteaser/job_classifier/pull/84
Reference : https://support.circleci.com/hc/en-us/articles/360007188574-Build-has-hit-timeout-limit

feat: Added no_output_timeout variable to Helm orb

---

orbs/e2e-web/orb.yml

Replace `circleci` orbs by `cimg` ones
We now need to use an other service to install drivers for browsers (see doc: https://circleci.com/developer/images/image/cimg/node)
I have tested manually browserstack and chrome following those changes:
- https://app.circleci.com/pipelines/github/jobteaser/e2e_jt_tests/21923/workflows/85ae38b5-9dca-48df-b556-7fbf44509b54/jobs/44644
- https://app.circleci.com/pipelines/github/jobteaser/e2e_jt_tests/21924/workflows/bb5c2026-5845-4b18-b649-a39af8a43ef8/jobs/44645

[QA ORB] Use nextgen orbs and browser tools utility for drivers

---

orbs/helm/orb.yml

So we can copy it to deploy by hand in case our workaround for the
docker images pulling issue doesn't work:
https://github.com/jobteaser/jobteaser/commit/abf15e643b706961b23d90422a67e80e0e61f3b3
https://jobteaser.slack.com/archives/CB2RB1DLM/p1631630805087600

feat: Print helm deploy command before running it

---

orbs/rb-service/orb.yml

There is no need to install `development` & `test` dependency on
the production docker image.
Update the `rb-service` orb with a `install_ruby_dependencies` command
with a new parameter `bundler_options` and when building the docker
image we use `--without development test`
[OP-1330]
[OP-1330]: https://jobteaser.atlassian.net/browse/OP-1330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(rb-service): Update orb for `bundle --without development test`

---

orbs/circleci/Dockerfile.concurrent
orbs/circleci/orb.yml
orbs/circleci/report-hold

[TRAIN-1220]
We've had issues in prod recently because we forgot to press the "Hold" button on a service deploy that was hence stuck in staging. When the frontend PR was deployed, things worked in staging, but not in prod.
It's not the first time we've forgotten to deploy something, so we'd like to be notified when a workflow stays on hold for too long.
Since we'll need it on several projects, we thought of making an orb directly.
It's basically a dependency-less ruby script that uses the CircleCI API to check if a workflow is on hold, and a Slack webhook to notify us.
I'm piggy-backing on the concurrent executor for convenience. I realize it's completely independent from concurrent concerns, but I'm wondering if it's worth creating and maintaining a new Docker image just for this (Ubuntu …

Add job to report workflows on hold for more than a day

---

orbs/circleci/report-hold

Small follow-up to #104 and #105, so we get feedback when nothing was found.

Add feedback when no workflow on hold found

---

orbs/go-service/orb.yml

I'm trying to use `gotestsum` instead of the standard go test command.
This will allow us to have junit reports, and other stuffs like
color highlighting for tests.
For that, I modified the existing test job to be able to store artifacts
and test results from gotestsum

feat(go-service): Modify the test job to store artifacts and test results

---

orbs/echoes/orb.yml

The present PR creates a new orb that will help in providing insights (part of [DORA metrics](https://cloud.google.com/blog/products/devops-sre/using-the-four-keys-to-measure-your-devops-performance)) about how frequently deployments are made (and whether they are successful or not). It relies on an [Echoes API](https://docs.echoeshq.com/releases) called "release" that the new orb calls to create a "release" each time a deployment workflow is triggered and to mark it as a "success" or a "failure" depending on its outcome.
Here is an example about how it would be used in a CircleCI config:
```
workflows:
version: 2
a_deployment_workflow_example:
- echoes/on-deployment-workflow-start:
name: "create_echoes_release"
filters:
branches:
only:
- master
- the_deployment_job:
context: "build"
- …
```

feat(echoes): create orb for Echoes release API

---

orbs/echoes/orb.yml

This PR fixes 2 different issues with the echoes orb:
1. we cannot rely on env variable CIRCLE_TAG to determine the commits list (not working on a re-run of a wf)
2. patching a release fails due to a missing env variable RELEASE_ID
No functional review expected. The new orb code has been partially tested here: https://app.circleci.com/pipelines/github/jobteaser/ui-jobteaser/22279/workflows/10c6fa0f-f553-4562-a99f-0ee01c5ec980

fix(echoes): empty commit list & fail to patch release status

---

orbs/echoes/orb.yml

This PR adds error handling for repositories that do not have tags at all (having tags is a prerequisites to determine the list of commits contained in a release).

fix(echoes-no-tags): handle issue with repos without tags

---

orbs/echoes/orb.yml

This PR add git-describe options to allow fallback to a commit if not enough tags exists.

fix(echoes-tags): handle issue with not enough tags available

---

orbs/echoes/orb.yml

This PR fixes API call to echoes used to patch a release. A header `content-type: application/json` was missing which failed the API call.

fix(orb-echoes): use json content type in PATCH API call

---

orbs/github/orb.yml

The present PR exposes a new `command` in `github` orb to enable / disable the restriction applied on a branch of a repository, preventing an admin from merging PRs without approval of other developers:
This command is especially handy in CI workflows where we want to "automerge" a PR (e.g.: for translations PR) using a github API token from an admin user.
No functional review is expected but you can see [here](https://app.circleci.com/pipelines/github/jobteaser/ui-jobteaser/23558/workflows/f7778ef7-251a-4bf5-95e7-0ab4f745b436/jobs/83858) a workflow where the new `command` have been tested and ran successfully.

feat(github): expose command to disable / enable admin restriction when merging a branch

---

orbs/docker/Dockerfile.build

Download Trivy DB for it to not be downloaded during the CI (It seems to hang on it a little bit)
If it works, we would have to auto build the image on dockerhub every ~ 6 hours 
This would gain 2 minutes on builds where trivy is used
Dockerfile change + trivy command tested in local

feat(docker): Download trivy db on build

---

orbs/helm-runner/orb.yml

The helm-runner orb only requires to checkout the k8s/ directory to apply configurations
Can win **1 minute** in each monolith CI run
Reference run : https://app.circleci.com/pipelines/github/jobteaser/jobteaser/44133/workflows/58e5074e-d5d3-4af2-b916-cb6c37aa55e6
Reference job : https://app.circleci.com/pipelines/github/jobteaser/jobteaser/44133/workflows/58e5074e-d5d3-4af2-b916-cb6c37aa55e6/jobs/1101625
"Git checkout" step --> 7s (Generally takes 1 to 1,5 minute)

feat(helm-runner): Customize checkout for deploy stages

---

orbs/phraseapp/orb.yml
orbs/phraseapp/utils/autocreate-phraseapp-pr

Adjust diff step to exclude the `.phrase.yml` file if it is the only file updated.
So it will avoid the creation of an unnecessary branch, with no associated PR.

fix(phrase): adjust diff step

---

doc/handbook.md
orbs/e2e-web/orb.yml

e2e_cookie parameter has been replaced by bypass_rack_attack_cookie parameter to be more explicit.
Constant variable $COOKIE_E2E replaced by $BYPASS_RACK_ATTACK.
Now we are using context e2e when executing e2e tests.

Update e2e web orb bypass rack attack cookie

---

doc/bootstrap.md
doc/handbook.md

Remove informations related to k8s certificate and emphasise usage of CircleCI contexts.

doc(k8s): Update docs relative to k8s certificates requirements

---

orbs/integration-test/orb.yml
orbs/pii/orb.yml

Execute "Get artifacts" command to always instead of on_success on orbs pii and integration-test.

UPDATE - Get artifacts when always
