orbs/go-service/orb.yml, orbs/rb-service/orb.yml, orbs/service/orb.yml
Close #4 
Can be fast-forward merged without squashing :)
=> Service orb

orbs/py-service/orb.yml
Will allow to set fixed reference in docker-compose for testing
=> Add double push to dockerhub

orbs/py-service/orb.yml
Will allow to set fixed reference in docker-compose for testing
=> Add double build to dockerhub

orbs/helm/orb.yml
Needed by: https://github.com/jobteaser/jobteaser/pull/13529
=> feat:add push to chartmuseum

orbs/helm/orb.yml
=> Add missing variables to lint step.

orbs/docker/orb.yml
=> Fix for issue #43

orbs/e2e-web/orb.yml
For e2e tests, we add now branch name to slack message
=> Add branch name to slack message

orbs/e2e-web/orb.yml
Remove slack orb and use script to add report URL to slack
=> Update e2e orbs for slack reporting optimization

orbs/helm/orb.yml
Remove Signalfx task as service is deprecated
=> Remove Signalfx event publish (#62)

doc/handbook.md
The documentation will be aligned with the current situation
=> doc: move from k8s secret to vault secret

orbs/git/orb.yml
Rational is in the orb's description.
=> Add new git orb with `custum_checkout` command

orbs/e2e-web/orb.yml
=> [Fix] Restore cache on e2e_jt_tests

orbs/rb-service/orb.yml
Then in each service we will want to get report, we will have to add rspec_opts to test.rake file: `--format RspecJunitFormatter --out test-results/rspec/results.xml`
And add in your GemFile the gem `rspec_junit_formatter'` in `group :test`
=> Add store artefact step for rb-service

orbs/circleci/orb.yml, orbs/circleci/report-hold
Turns out the interpolation I was trying to do in #104 didn't work
This has been tested successfully on jobteaser/notification#31
=> Fix report_hold job

orbs/helm-runner/circle-wait-job, orbs/helm-runner/deployable, orbs/helm-runner/orb.yml
working orb deployment: https://app.circleci.com/pipelines/github/jobteaser/vds/1009/workflows/cbd93711-b368-45e5-b2dd-dc61acacab38/jobs/1473
=> feat(helm/runner): new helm deploy with runner

orbs/docker/orb.yml
use docker v20, buildkit, and push docker & harbor simultaneously
=> feat(docker): use docker v20, buildkit, and push docker & harbor simultaneously

orbs/pii/orb.yml
Create an orb to execute PII tests on each microservice.
**When using the pii orb, you have to pass following parameters:**
- service (service name)
- channel_id (Slack channel id retrieve from Copy link on srv-<service name>-dev slack channel)
**PII tests executed on service:**
- Execute tests on List of PII descriptions on service
- Execute tests on Get User PII on existing user on service
- Create user AND Execute tests on Get User PII on created user on service
- Delete user AND Execute tests on Get User PII on deleted user on service
=> Add pii orb

orbs/e2e-web/orb.yml, orbs/integration-test/orb.yml, orbs/pii/orb.yml
- Update version circleci/browser-tools
- Update orb e2e-web
- execute e2e tests depending on browser
- remove step verify tracking (new implementation on e2e_jt_tests repo)
- Update orb pii
- replace existing chrome
- change executor size to small
- add store result on e2e tests
- Create orb integration-test
=> UPDATE - orbs e2e-web, integration-test and pii

orbs/pii/orb.yml
execute_list_pii_descriptions_tests
execute_pii_tests_on_existing_user
=> ADD - new jobs on pii orb

orbs/e2e-web/orb.yml
- Update service version
- Update create_report_folder and slack_alerting commands
- Remove verify_tracking command
=> UPDATE - e2e-web orb
